name: Dependabot auto-merge
on:
  pull_request:
    types: [opened, reopened]

permissions:
    contents: write
    pull-requests: write

jobs:
  dependabot:
    uses: jimbrig/ghactions/.github/workflows/dependabot-merge.yml@main
