name: Sync-GHLabels
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/labels.yml
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
